### ISSUE TITLE
[Question Feedback] How many developers at your company are responsible for writing Ember code?

### ISSUE THREAD

**Issue by Turbo87** [ember-learn/annual-community-survey#26]
This question is only asking about the total amount, but it gives us no insight into the relative amount. Should we add a similar question that asks about the total company size?

**Comment by GavinJoyce** [comment]
We also seem to only be asking people who pick the `101-500` option to encourage their colleagues. Perhaps this should be moved out of an individual option?

<img width="929" alt="screen shot 2019-02-14 at 14 35 30" src="https://user-images.githubusercontent.com/2526/52793506-ccf5c600-3065-11e9-8244-03474d9322d3.png">

**Comment by mixonic** [comment]
I think this is a poor place to call out encouragement regardless. We 
directly contact big employers and encourage internal participation, that 
and announcement materials seems the proper spot for outreach messaging.

**Comment by josephdsumner** [comment]
Resolved issues in this discussion, thanks! :+1:
