### ISSUE TITLE
[Question Feedback] What testing framework(s) do you use in your Ember apps?

### ISSUE THREAD

**Issue by Turbo87** [ember-learn/annual-community-survey#28]
the answers should be adjusted slightly:

- Mocha (via `ember-mocha` or `ember-cli-mocha`)
- QUnit (via `ember-qunit` or `ember-cli-qunit`)

(Please don't capitalize project names unless they are officially written that way 😉)

**Comment by josephdsumner** [comment]
Resolved, thanks! :+1:
